### ISSUE TITLE
error opening build.exe

### ISSUE THREAD

**Issue by fenixz176** [f4kedre4lity/Blank-Grabber#36]
Traceback (most recent call last):
  File "C:\Users\Guilherme\Downloads\Blank-Grabber-main\Blank Grabber\gui.py", line 12, in <module>
    import customtkinter as ctk
  File "C:\Users\Guilherme\AppData\Local\Programs\Python\Python312\Lib\site-packages\customtkinter\__init__.py", line 10, in <module>
    from .windows.widgets.appearance_mode import AppearanceModeTracker
  File "C:\Users\Guilherme\AppData\Local\Programs\Python\Python312\Lib\site-packages\customtkinter\windows\__init__.py", line 1, in <module>
    from .ctk_tk import CTk
  File "C:\Users\Guilherme\AppData\Local\Programs\Python\Python312\Lib\site-packages\customtkinter\windows\ctk_tk.py", line 2, in <module>
    from distutils.version import StrictVersion as Version
ModuleNotFoundError: No module named 'distutils'

**Comment by noahmajors** [comment]
pip install customtkinter

run again

**Comment by fenixz176** [comment]
dont worked

**Comment by fenixz176** [comment]
said requirement already satisfied and when I opened it it gave the same error

**Comment by fenixz176** [comment]
![Screenshot_1](https://github.com/f4kedre4lity/Blank-Grabber/assets/147442530/597907ee-4739-4dd1-9ab1-6330563ffa91)

**Comment by fenixz176** [comment]
I managed to solve it thank you

**Comment by BumiMandiasDev** [comment]
Would be nice if you'd say how you solved it (for others)

**Comment by fenixz176** [comment]
I didn't solve it

**Comment by Jazz1254** [comment]
Can someone please explain what we need to do?
