### ISSUE TITLE
Blank Grabber It gave an error while opening the setup

### ISSUE THREAD

**Issue by Jazz1254** [f4kedre4lity/Blank-Grabber#43]
Traceback (most recent call last):
  File "C:\Users\GamerX\Desktop\r4t\Blank Grabber\gui.py", line 12, in <module>
    import customtkinter as ctk
  File "C:\Users\GamerX\AppData\Local\Programs\Python\Python312\Lib\site-packages\customtkinter\__init__.py", line 10, in <module>
    from .windows.widgets.appearance_mode import AppearanceModeTracker
  File "C:\Users\GamerX\AppData\Local\Programs\Python\Python312\Lib\site-packages\customtkinter\windows\__init__.py", line 1, in <module>
    from .ctk_tk import CTk
  File "C:\Users\GamerX\AppData\Local\Programs\Python\Python312\Lib\site-packages\customtkinter\windows\ctk_tk.py", line 7, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'

**Comment by Jazz1254** [comment]
What should I do?

**Comment by Linkzone6** [comment]
Solution: pip3 install packaging 
 also a pro tip, make sure you are on python 3.11.0

> I also got the same error how to fix it?



> What should I do?
