### ISSUE TITLE
problem with building exe

### ISSUE THREAD

**Issue by AkyAwens** [f4kedre4lity/Blank-Grabber#45]
Traceback (most recent call last):
  File "C:\Users\HeavenDev\Desktop\Blank Grabber\env\Scripts\process.py", line 9, in <module>
    import pyaes
ModuleNotFoundError: No module named 'pyaes'
239 INFO: PyInstaller: 6.1.0
242 INFO: Python: 3.12.0
266 INFO: Platform: Windows-10-10.0.19045-SP0
267 INFO: wrote C:\Users\HeavenDev\Desktop\Blank Grabber\env\Scripts\Built.exe.spec
285 INFO: UPX is available and will be used if enabled on build targets.
285 INFO: Removing temporary files and cleaning cache in C:\Users\HeavenDev\AppData\Local\pyinstaller
script 'C:\Users\HeavenDev\Desktop\Blank Grabber\env\Scripts\loader-o.py' not found
![image](https://github.com/f4kedre4lity/Blank-Grabber/assets/131627428/fc142872-dec1-43b9-909c-db4bf54bf020)

**Comment by 2020673** [comment]
Traceback (most recent call last): 
  File "C:\Users\simontrain\Desktop\Blank-Grabber-main\Blank Grabber\gui.py", line 883, in <module> 
    Utility.CheckConfiguration() 
  File "C:\Users\simontrain\Desktop\Blank-Grabber-main\Blank Grabber\gui.py", line 87, in CheckConfiguration 
    config = json.load(file) 
             ^^^^^^^^^^^^^^^ 
  File "C:\Users\simontrain\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load 
    return loads(fp.read(), 
           ^^^^^^^^^^^^^^^^ 
  File "C:\Users\simontrain\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads 
    return _default_decoder.decode(s) 
           ^^^^^^^^^^^^^^^^^^^^^^^^^^ 
  File "C:\Users\simontrain\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode 
    obj, end = self.raw_decode(s, idx=_w(s, 0).end()) 
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
  File "C:\Users\simontrain\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode 
    raise JSONDecodeError("Expecting value", s, err.value) from None 
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0

**Comment by PH7N** [comment]
Google en passant
