### ISSUE TITLE
Got a error code anyone able to help?

### ISSUE THREAD

**Issue by BlitzFan1209** [f4kedre4lity/Blank-Grabber#63]
![image](https://github.com/f4kedre4lity/Blank-Grabber/assets/98890042/b96b5cf8-e0f3-446c-8d09-1fde56270263)
Traceback (most recent call last):
  File "C:\Users\User\Downloads\Blank-Grabber-main\Blank-Grabber-main\Blank Grabber\gui.py", line 14, in <module>
    from pkg_resources import parse_version
ModuleNotFoundError: No module named 'pkg_resources'

**Comment by BlitzFan1209** [comment]
got it working but now got this
Traceback (most recent call last):
  File "C:\Users\User\Downloads\Blank-Grabber-main\Blank-Grabber-main\Blank Grabber\env\Scripts\process.py", line 9, in <module>
    import pyaes
ModuleNotFoundError: No module named 'pyaes'
600 INFO: PyInstaller: 5.10.1
601 INFO: Python: 3.10.7
612 INFO: Platform: Windows-10-10.0.19045-SP0
614 INFO: wrote C:\Users\User\Downloads\Blank-Grabber-main\Blank-Grabber-main\Blank Grabber\env\Scripts\Built.exe.spec
642 INFO: UPX is available.
642 INFO: Removing temporary files and cleaning cache in C:\Users\User\AppData\Local\pyinstaller
script 'C:\Users\User\Downloads\Blank-Grabber-main\Blank-Grabber-main\Blank Grabber\env\Scripts\loader-o.py' not found

**Comment by 555XF** [comment]
This is the same error i have could never find a solution :(

**Comment by 555XF** [comment]
> got it working but now got this Traceback (most recent call last): File "C:\Users\User\Downloads\Blank-Grabber-main\Blank-Grabber-main\Blank Grabber\env\Scripts\process.py", line 9, in import pyaes ModuleNotFoundError: No module named 'pyaes' 600 INFO: PyInstaller: 5.10.1 601 INFO: Python: 3.10.7 612 INFO: Platform: Windows-10-10.0.19045-SP0 614 INFO: wrote C:\Users\User\Downloads\Blank-Grabber-main\Blank-Grabber-main\Blank Grabber\env\Scripts\Built.exe.spec 642 INFO: UPX is available. 642 INFO: Removing temporary files and cleaning cache in C:\Users\User\AppData\Local\pyinstaller script 'C:\Users\User\Downloads\Blank-Grabber-main\Blank-Grabber-main\Blank Grabber\env\Scripts\loader-o.py' not found

This is the same error i have could never find a solution :(

**Comment by KuebelHund** [comment]
try this: "pip install pyaes" because its obviously missing

**Comment by 555XF** [comment]
> try this: "pip install pyaes" because its obviously missing

already have pip installed still doesnt work either way

**Comment by KuebelHund** [comment]
Im not speaking of installing pip, im speaking of USING pip to install "pyaes".
Open your commandline and type this: "pip install pyaes". That way youre using pip to install the pyaes package.

**Comment by thatoneuser41** [comment]
> Im not speaking of installing pip, im speaking of USING pip to install "pyaes". Open your commandline and type this: "pip install pyaes". That way youre using pip to install the pyaes package.

kk ty fixed the problem lol (btw u might have to upgrade pip first like I did)

**Comment by 555XF** [comment]
> Im not speaking of installing pip, im speaking of USING pip to install "pyaes". Open your commandline and type this: "pip install pyaes". That way youre using pip to install the pyaes package.

i meant pyaes not pip cuz I've already installed pyaes and it still doesn't work for some random unknown reason
